# Copyright (c) 2024 Di-Is
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php
#

[tool.pytest.ini_options]
# Exclude external_module_test.py & common_faiss_tests.py
python_files = "test_*.py"
