line-length = 99
indent-width = 4

target-version = "py39"

exclude = ["./faiss"]

[lint]
ignore = [
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "ANN101",
    "ANN102",
]
select = ["ALL"]
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true
docstring-code-line-length = 88
