name: Bug report
description: Report an error or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: This project supports Compute capability 7.0-8.9 (Volta, Turing, Ampere, Ada Lovelace) GPU architectures.**
        Please read the [README.md](https://github.com/Di-Is/faiss-gpu-wheels) first.

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug, including a minimal reproducible example.
        Please include the full error message and output.
    validations:
      required: true

  - type: input
    attributes:
      label: Platform
      description: What OS and architecture? (see `uname -orsm`)
      placeholder: e.g., Ubuntu 22.04 x86_64, macOS 14 arm64
    validations:
      required: true

  - type: input
    attributes:
      label: GPU model
      description: GPU model (see `nvidia-smi`)
      placeholder: e.g., NVIDIA RTX 3080, NVIDIA A100-40GB
    validations:
      required: true

  - type: input
    attributes:
      label: NVIDIA Driver version
      description: Driver version (see `nvidia-smi`)
      placeholder: e.g., 535.104.12
    validations:
      required: true

  - type: input
    attributes:
      label: Package version
      description: Which package and version? (see `pip show faiss-gpu-cu11` or `faiss-gpu-cu12`)
      placeholder: e.g., faiss-gpu-cu12 1.8.0
    validations:
      required: true

  - type: input
    attributes:
      label: CUDA runtime version
      description: Version of nvidia-cuda-runtime (see `pip show nvidia-cuda-runtime-cu11` or `cu12`)
      placeholder: e.g., 12.1.105
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      description: What version of Python? (see `python --version`)
      placeholder: e.g., Python 3.10.12
    validations:
      required: true
