name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Please note: Feature requests for FAISS core functionality should be submitted to the [Upstream FAISS repository](https://github.com/facebookresearch/faiss).**
        This repository is for wheel packaging and distribution only.

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of what new feature or behavior you would like to see.
        If applicable, please describe the current behavior as well.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example
      description: Provide an example of how the user experience would change or how the new feature would be used.
    validations:
      required: false
