[python]
preload-library = []

[test]
# torch 2.7.0 is not compatible with python 3.9
dependencies = ["pytest", "pytest-xdist", "scipy", "torch<2.7.0"]
index-url = "https://download.pytorch.org/whl/cpu"
