image = "manylinux2014_x86_64"
opt-level = "generic"
variant = "cpu"

[cxx]
njob = 32

[python]
njob = 4
requires-python = ">=3.9,<=3.12"
preload-library = []

[[python.test]]
name = "import_test"
image = "fedora:40"
target-python-versions = ["3.12"]
install-command = []
test-command = ["python", "-c", "'import faiss'"]

[[python.test]]
name = "faiss_test"
image = "quay.io/pypa/manylinux2014_x86_64"
target-python-versions = ["3.9", "3.10", "3.11", "3.12"]
test-command = ["pytest", "faiss/tests", "-n", "8"]
install-command = ["pytest", "scipy", "pytest-xdist"]

[[python.test]]
name = "torch_contrib_test"
image = "quay.io/pypa/manylinux2014_x86_64"
target-python-versions = ["3.9", "3.10", "3.11", "3.12"]
test-command = ["pytest", "-s", "faiss/tests/torch_test_contrib.py", "-n", "8"]
install-command = [
    "pytest",
    "scipy",
    "pytest-xdist",
    "torch",
    "--extra-index-url",
    "https://download.pytorch.org/whl/cpu",
]
